name: Deploy Lambda

on:
  push:
    branches:
      - main     # deploy produção
      - develop  # deploy dev

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Cache PNPM store
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Instalar PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Instalar dependências
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Remover node_modules e instalar apenas produção
        run: rm -rf node_modules && pnpm install --prod

      - name: Empacotar Lambda
        run: zip -r function.zip dist node_modules

      - name: Deploy Lambda
        run: |
          aws lambda update-function-code \
            --function-name aws-lambda-queue-consumer \
            --zip-file fileb://function.zip \
            --region us-east-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
